server:
  port: 8081
  servlet:
    context-path: /order-service
spring:
  application:
    name: order-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:53697/mydatabase
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  reactor:
    debug-agent:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/product-service
      client:
        registration:
          keycloak:
            client-id: order-service-client
            client-secret: ${secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/product-service

  config:
    import: vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: 00000000-0000-0000-0000-000000000000
      scheme: http
      kv:
        enabled: true
        default-context: gs-vault-config
        backend: secret

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  oauth2:
    enabled: true
    clientRegistrationId: keycloak

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG